import {
  ADMIN_ASSIGNABLE_ROLES,
  ALL_ROLES,
  Role,
  type Permission,
  type RBACContext,
} from "@/types/rbac";

export { Role, type Permission, type RBACContext } from "@/types/rbac";

const ROLE_PERMISSIONS: Record<Role, ReadonlySet<Permission>> = {
  [Role.Guest]: new Set([]),
  [Role.Member]: new Set([
    "problem.view",
    "problem.create",
    "problem.edit.own",
    "problem.delete.own",
    "problem.search",
    "comment.view",
    "comment.create",
    "vote.create",
    "insight.view",
    "pitch.view",
    "pitch.create",
    "pitch.edit.own",
    "pitch.submit",
    "pitch.ai.analyze",
    "team.view",
    "team.skills.view",
    "team.availability.view",
    "analysis.view",
    "mentor.view",
    "mentorship.request.create",
    "mentorship.request.view.own",
    "mentoring.session.view.own",
    "mentoring.progress.view.own",
    "mentoring.feedback.create",
    "mentoring.communication.create",
    "task.view",
    "task.create",
    "task.edit.own",
    "task.delete.own",
    "task.assign",
    "task.status.change",
    "milestone.view",
    "project.activity.view",
    "project.metrics.view",
    "workspace.view",
    "workspace.progress.view",
    "community.view",
    "profile.edit.own",
    "notifications.view",
  ]),
  [Role.Builder]: new Set([
    "problem.view",
    "problem.create",
    "problem.edit.own",
    "problem.delete.own",
    "problem.search",
    "comment.view",
    "comment.create",
    "vote.create",
    "insight.view",
    "pitch.view",
    "pitch.create",
    "pitch.edit.own",
    "pitch.submit",
    "pitch.ai.analyze",
    "team.view",
    "team.skills.view",
    "team.availability.view",
    "analysis.view",
    "mentor.view",
    "mentorship.request.create",
    "mentorship.request.view.own",
    "mentoring.session.view.own",
    "mentoring.progress.view.own",
    "mentoring.feedback.create",
    "mentoring.communication.create",
    "task.view",
    "task.create",
    "task.edit.own",
    "task.delete.own",
    "task.assign",
    "task.status.change",
    "milestone.view",
    "project.activity.view",
    "project.metrics.view",
    "workspace.view",
    "workspace.progress.view",
    "community.view",
    "profile.edit.own",
    "notifications.view",
  ]),
  [Role.Expert]: new Set([
    "problem.view",
    "problem.create",
    "problem.edit.own",
    "problem.delete.own",
    "problem.search",
    "comment.view",
    "comment.create",
    "vote.create",
    "insight.view",
    "insight.generate",
    "insight.expert_mode",
    "pitch.view",
    "pitch.create",
    "pitch.edit.own",
    "pitch.submit",
    "pitch.ai.analyze",
    "pitch.feedback",
    "team.view",
    "team.skills.view",
    "team.availability.view",
    "analysis.view",
    "analysis.create",
    "analysis.edit.own",
    "analysis.delete.own",
    "analysis.scorecard.create",
    "analysis.scorecard.edit.own",
    "mentor.view",
    "mentor.profile.create",
    "mentor.profile.edit.own",
    "mentorship.request.create",
    "mentorship.request.view.own",
    "mentoring.session.create",
    "mentoring.session.view.own",
    "mentoring.session.edit.own",
    "mentoring.progress.create",
    "mentoring.progress.view.own",
    "mentoring.progress.edit.own",
    "mentoring.feedback.create",
    "mentoring.communication.create",
    "task.view",
    "task.create",
    "task.edit.own",
    "task.delete.own",
    "task.assign",
    "task.status.change",
    "milestone.view",
    "project.activity.view",
    "project.metrics.view",
    "workspace.view",
    "workspace.progress.view",
    "community.view",
    "profile.edit.own",
    "notifications.view",
  ]),
  [Role.Mentor]: new Set([
    "problem.view",
    "problem.create",
    "problem.edit.own",
    "problem.search",
    "comment.view",
    "comment.create",
    "vote.create",
    "discussion.ai_summary",
    "insight.view",
    "insight.generate",
    "insight.regenerate",
    "insight.expert_mode",
    "pitch.view",
    "pitch.create",
    "pitch.edit.own",
    "pitch.submit",
    "pitch.ai.analyze",
    "pitch.feedback",
    "team.view",
    "team.skills.view",
    "team.availability.view",
    "task.assign",
    "analysis.view",
    "analysis.create",
    "analysis.edit.own",
    "analysis.delete.own",
    "analysis.scorecard.create",
    "analysis.scorecard.edit.own",
    "mentor.view",
    "mentor.profile.create",
    "mentor.profile.edit.own",
    "mentorship.request.view.any",
    "mentorship.request.manage",
    "mentoring.session.create",
    "mentoring.session.view.own",
    "mentoring.session.edit.own",
    "mentoring.progress.create",
    "mentoring.progress.view.own",
    "mentoring.progress.edit.own",
    "mentoring.feedback.create",
    "mentoring.communication.create",
    "task.view",
    "task.create",
    "task.edit.own",
    "task.delete.own",
    "task.assign",
    "task.status.change",
    "milestone.view",
    "project.activity.view",
    "project.metrics.view",
    "workspace.view",
    "workspace.progress.view",
    "community.view",
    "profile.edit.own",
    "notifications.view",
  ]),
  [Role.Leader]: new Set([
    "problem.view",
    "problem.create",
    "problem.edit.own",
    "problem.edit.any",
    "problem.delete.any",
    "problem.categories.manage",
    "problem.search",
    "comment.view",
    "comment.create",
    "vote.create",
    "comment.delete.others",
    "discussion.ai_summary",
    "insight.view",
    "insight.generate",
    "insight.regenerate",
    "insight.expert_mode",
    "pitch.view",
    "pitch.create",
    "pitch.edit.any",
    "pitch.approve",
    "pitch.reject",
    "pitch.start_review",
    "pitch.convert",
    "pitch.ai.analyze",
    "pitch.feedback",
    "team.view",
    "team.invite",
    "team.remove",
    "team.role.change",
    "team.skills.view",
    "team.skills.manage",
    "team.availability.view",
    "team.analytics.view",
    "workspace.view",
    "task.create",
    "task.assign",
    "workspace.progress.view",
    "project.create",
    "project.edit",
    "project.archive",
    "member.manage",
    "workflow.generate",
    "report.generate",
    "analysis.view",
    "analysis.create",
    "analysis.edit.any",
    "analysis.delete.any",
    "analysis.publish",
    "analysis.scorecard.create",
    "analysis.scorecard.edit.any",
    "mentor.view",
    "mentorship.request.create",
    "mentorship.request.view.any",
    "mentorship.request.manage",
    "mentoring.session.create",
    "mentoring.session.view.own",
    "mentoring.progress.create",
    "mentoring.progress.view.own",
    "mentoring.feedback.create",
    "mentoring.communication.create",
    "task.view",
    "task.create",
    "task.edit.any",
    "task.delete.any",
    "task.assign",
    "task.status.change",
    "milestone.view",
    "milestone.create",
    "milestone.edit.any",
    "milestone.delete.any",
    "project.activity.view",
    "project.metrics.view",
    "community.view",
    "profile.edit.own",
    "notifications.view",
  ]),
  [Role.Admin]: new Set([
    "problem.view",
    "problem.create",
    "problem.edit.own",
    "problem.edit.any",
    "problem.delete.own",
    "problem.delete.any",
    "problem.categories.manage",
    "problem.search",
    "comment.view",
    "comment.create",
    "vote.create",
    "comment.delete.others",
    "discussion.ai_summary",
    "insight.view",
    "insight.generate",
    "insight.regenerate",
    "insight.expert_mode",
    "pitch.view",
    "pitch.create",
    "pitch.edit.any",
    "pitch.delete.any",
    "pitch.approve",
    "pitch.reject",
    "pitch.start_review",
    "pitch.convert",
    "pitch.ai.analyze",
    "pitch.feedback",
    "team.view",
    "team.invite",
    "team.remove",
    "team.role.change",
    "team.skills.view",
    "team.skills.manage",
    "team.availability.view",
    "team.availability.manage",
    "team.analytics.view",
    "workspace.view",
    "settings.view",
    "settings.edit",
    "settings.ai.manage",
    "settings.workflow.manage",
    "settings.notification.manage",
    "settings.security.manage",
    "audit.logs.view",
    "users.view",
    "users.edit",
    "users.role.change",
    "users.status.change",
    "users.delete",
    "task.create",
    "task.assign",
    "task.update.own",
    "workspace.progress.view",
    "project.create",
    "project.delete",
    "project.edit",
    "project.archive",
    "member.manage",
    "workflow.generate",
    "report.generate",
    "analysis.view",
    "analysis.create",
    "analysis.edit.any",
    "analysis.delete.any",
    "analysis.publish",
    "analysis.scorecard.create",
    "analysis.scorecard.edit.any",
    "mentor.view",
    "mentor.profile.create",
    "mentor.profile.edit.own",
    "mentorship.request.view.any",
    "mentorship.request.manage",
    "mentoring.session.create",
    "mentoring.session.view.own",
    "mentoring.progress.create",
    "mentoring.progress.view.own",
    "mentoring.feedback.create",
    "mentoring.communication.create",
    "task.view",
    "task.create",
    "task.edit.any",
    "task.delete.any",
    "task.assign",
    "task.status.change",
    "milestone.view",
    "milestone.create",
    "milestone.edit.any",
    "milestone.delete.any",
    "project.activity.view",
    "project.metrics.view",
    "community.view",
    "profile.edit.own",
    "notifications.view",
    "user.role.change",
    "admin.panel.view",
    "user.delete",
  ]),
};

const CONTEXT_RULES: Partial<Record<Permission, (ctx: RBACContext) => boolean>> = {
  "problem.edit.own": (ctx) => ctx.isOwner === true,
  "problem.delete.own": (ctx) => ctx.isOwner === true,
  "pitch.edit.own": (ctx) =>
    ctx.isOwner === true &&
    (ctx.pitchStatus === "pending" || ctx.pitchStatus === "draft" || ctx.pitchStatus === "submitted"),
  "task.update.own": (ctx) => ctx.isAssignee === true,
  "workspace.view": (ctx) =>
    ctx.isProjectMember === true || ctx.isProjectLeader === true || ctx.role === Role.Admin,
  "task.create": (ctx) =>
    ctx.isProjectMember === true || ctx.role === Role.Admin,
  "workspace.progress.view": (ctx) =>
    ctx.isProjectMember === true || ctx.role === Role.Admin,
  "project.edit": (ctx) =>
    ctx.isProjectLeader === true || ctx.role === Role.Admin,
  "project.archive": (ctx) =>
    ctx.isProjectLeader === true || ctx.role === Role.Admin,
  "member.manage": (ctx) =>
    ctx.isProjectLeader === true || ctx.role === Role.Admin,
  "workflow.generate": (ctx) =>
    ctx.isProjectLeader === true || ctx.role === Role.Admin,
  "report.generate": (ctx) =>
    ctx.isProjectLeader === true || ctx.role === Role.Admin,
  "task.assign": (ctx) =>
    ctx.isProjectMember === true || ctx.role === Role.Mentor || ctx.role === Role.Admin,
  "profile.edit.own": (ctx) => ctx.isAuthenticated,
  "notifications.view": (ctx) => ctx.isAuthenticated,
};

export function parseRole(value: string | null | undefined): Role {
  if (!value) {
    return Role.Member;
  }

  const normalized = value.toLowerCase() as Role;
  return ALL_ROLES.includes(normalized) ? normalized : Role.Member;
}

export function hasRole(role: Role, allowed: Role | Role[]): boolean {
  const allowedRoles = Array.isArray(allowed) ? allowed : [allowed];
  return allowedRoles.includes(role);
}

export function hasPermission(ctx: RBACContext, permission: Permission): boolean {
  if (ctx.role === Role.Admin) {
    return true;
  }

  const rolePermissions = ROLE_PERMISSIONS[ctx.role];
  if (!rolePermissions?.has(permission)) {
    return false;
  }

  const contextRule = CONTEXT_RULES[permission];
  if (contextRule) {
    return contextRule(ctx);
  }

  return true;
}

export function canAssignRole(actorRole: Role, targetRole: Role): boolean {
  if (actorRole !== Role.Admin) {
    return false;
  }

  return ADMIN_ASSIGNABLE_ROLES.includes(targetRole) || targetRole === Role.Member || targetRole === Role.Admin;
}

export function getPermissionsForRole(role: Role): Permission[] {
  return Array.from(ROLE_PERMISSIONS[role] ?? []);
}

export function createAuthenticatedContext(
  role: Role,
  userId: string,
  overrides: Partial<RBACContext> = {}
): RBACContext {
  return {
    role,
    userId,
    isAuthenticated: true,
    ...overrides,
  };
}

export function createGuestContext(): RBACContext {
  return {
    role: Role.Guest,
    isAuthenticated: false,
  };
}

export function getWorkspacePermissions(ctx: RBACContext) {
  return {
    canViewWorkspace: hasPermission(ctx, "workspace.view"),
    canCreateTask: hasPermission(ctx, "task.create"),
    canAssignTask: hasPermission(ctx, "task.assign"),
    canUpdateOwnTask: hasPermission(ctx, "task.update.own"),
    canViewProgress: hasPermission(ctx, "workspace.progress.view"),
    canCreateProject: hasPermission(ctx, "project.create"),
    canDeleteProject: hasPermission(ctx, "project.delete"),
    canEditProject: hasPermission(ctx, "project.edit"),
    canArchiveProject: hasPermission(ctx, "project.archive"),
    canManageMembers: hasPermission(ctx, "member.manage"),
    canGenerateWorkflow: hasPermission(ctx, "workflow.generate"),
    canGenerateReport: hasPermission(ctx, "report.generate"),
  };
}

export const NAV_PERMISSIONS: Partial<Record<string, Permission>> = {
  "/dashboard": "community.view",
  "/dashboard/problems": "problem.view",
  "/dashboard/discussion": "comment.view",
  "/dashboard/insights": "insight.view",
  "/dashboard/workspace": "workspace.view",
  "/dashboard/archive": "workspace.progress.view",
  "/dashboard/admin": "admin.panel.view",
};
